### ISSUE TITLE
Мир Готики 1

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g1_russobit-m_fix#1]
А ты мир правила в своём фиксе?

**Comment by dosinabox** [comment]
да

**Comment by Kor-Angar** [comment]
ты не против если я его использую для своей сборки ?

**Comment by dosinabox** [comment]
бери, конечно

**Comment by Kor-Angar** [comment]
ты его правила в каком то новом редакторе?

**Comment by Kor-Angar** [comment]
не скинешь мир, а то у меня что то не получается распаковать инсталер.

**Comment by dosinabox** [comment]
> ты его правила в каком то новом редакторе?

В стандартном Spacer. Тогда никаких новых не было.

> не скинешь мир, а то у меня что то не получается распаковать инсталер.

[WORLD.zip](https://github.com/dosinabox/g1_russobit-m_fix/files/7112359/WORLD.zip)
