### ISSUE TITLE
ОФФ топ

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g1_russobit-m_fix#4]
...

**Comment by Kor-Angar** [comment]
никогда если честно не играл в Руссобит версию. перевыпуск игры без каких либо на то причин был как минимум странен :-)

вот буду первый раз пробовать с переводом Руссобит :-)

на память.

- [RU_AAI_description.zip](https://github.com/dosinabox/g1_russobit-m_fix/files/8073604/RU_AAI_description.zip)
- [RU_DIA_description.zip](https://github.com/dosinabox/g1_russobit-m_fix/files/8073605/RU_DIA_description.zip)

**Comment by dosinabox** [comment]
Ну как без причин. Впервые официально. И без вырезанного концерта.

**Comment by dosinabox** [comment]
Лично я воспринимаю перевод только от Руссобита, потому что он был первым) А от Снежков так и не удалось поиграть толком.

**Comment by Kor-Angar** [comment]
> Впервые официально. 

это как? впервые официально же был перевод от снежков.

> И без вырезанного концерта.

проще было выпустить диккурик,  патч для игры и диск музыкой. диккурик  кстати они переводили? :-)

**Comment by dosinabox** [comment]
> впервые официально же был перевод от снежков.

Без разрешения (по пиратски). И разработчики с этого ничего не имели. Кажется, так.

> диккурик кстати они переводили? :-)

Да, и полностью озвучили теми же актерами.
Только вот мод без концовки) Не доделан.

**Comment by Kor-Angar** [comment]
> Без разрешения (по пиратски). И разработчики с этого ничего не имели. Кажется, так.

там же издатель 1с был. поэтому они и концерт вырезали, так как выпустили его официально ;-)
[Manual.zip](https://github.com/dosinabox/g1_russobit-m_fix/files/8073730/Manual.zip)

![image](https://user-images.githubusercontent.com/49514764/154127287-4fb42e8f-46d3-49e1-a584-8dbcbfea3702.png)

**Comment by dosinabox** [comment]
> там же издатель 1с был

Это было интересное время)

> поэтому они и концерт вырезали, так как выпустили его официально

Концерта нет, потому что переводили с английской версии. А для американского рынка концерт вырезали из-за прав.

**Comment by Kor-Angar** [comment]
```D
NAME_LEARNMANA_1 = "Магическая сила +1";
NAME_LEARNMANA_5 = "Магическая сила +5";
NAME_LEARNMANA_10 = "Магическая сила +10";
NAME_LEARNMANA_20 = "Магическая сила +20";
```
это мана?

[RU_text.zip](https://github.com/dosinabox/g1_russobit-m_fix/files/8074224/RU_text.zip)

**Comment by Kor-Angar** [comment]
Зато я наконец смогу локализацию полноценно протестить.  Так как на немецкие скрипты ставить русский перевод это намного понятнее чем на русский ставить немецкий 😂

**Comment by dosinabox** [comment]
> это мана?

да

**Comment by Kor-Angar** [comment]
> Без разрешения (по пиратски).

тогда странно где они достали дистрибутивы английской версии, ведь первая появилась пиратка с немецкой версии. видимо всё таки им один из издателей дал разрешение и права.

***

а я начинал играть с пираток. с прекрасным немецкой озвучкой :-) и с косяками из первых верский

***

[RU_NPC_name.zip](https://github.com/dosinabox/g1_russobit-m_fix/files/8076583/RU_NPC_name.zip)

**Comment by Kor-Angar** [comment]
> Без разрешения (по пиратски).
> Это было интересное время)

1с бы засудили и сняли бы много денег если бы у них разрешения не было. даже сейчас. если бы кто решил так поступить в "святые 90ые" то использовал бы или новое юр. лицо.  или делал бы это в чёрное.

я даже как физ. лицо. подвергся судебным процессам за нарушение использования товарных знаков, был оштрафован, возбуждены судебные производства, арестованы счета физ лиц как в россии так и в азии. и это как физ. лицо  до которого гораздо сложнее дотянуться правообладателям. 
засудить такую компанию как 1С, это очень просто. особенно если делать это из европы. просто потом спишут средства с валютных счетов и всё.

**Comment by Kor-Angar** [comment]
очень интересный перевод "ende" . да ещё и c капслуком.  теперь я понимаю почему у тебя в НВ, такие странные надписи порой встречаются :-)

![20220216103215_1](https://user-images.githubusercontent.com/49514764/154217426-2b0a5768-77ac-475e-bfd6-6387f549ce8b.jpg)


[DIA_description_DIALOG_ENDE.zip](https://github.com/dosinabox/g1_russobit-m_fix/files/8077702/DIA_description_DIALOG_ENDE.zip)

**Comment by Kor-Angar** [comment]
всё таки всем кто начинает с оригинальной игры, проще потом воспринимать локализации :-)

**Comment by Kor-Angar** [comment]
по моему руссобит делал перевод с английской версии :-)Message ID: ***@***.***>

**Comment by Kor-Angar** [comment]
а можно конверировать в дискуссию?

**Comment by Kor-Angar** [comment]
млин у Руссобит Юберион. а в англ. версии как?
